[build]
  command = "npm install @supabase/supabase-js && npm install --save-dev @types/node && npx vite build"
  publish = "dist"

# If you need to set environment variables for all deploys
[build.environment]
  NODE_VERSION = "18.19.0"

# Redirects for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
