[build]
  command = "npm install && npm run build:vite-only"
  publish = "dist"

# Force clear cache
[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"
  NETLIFY_USE_YARN = "false"
  NETLIFY_SKIP_CACHE = "true"

# SPA redirect - MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200