[build]
  command = "npm install && npm run build"
  publish = "dist"

# If you need to set environment variables for all deploys
[build.environment]
  NODE_VERSION = "18.19.0"

# Redirects for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
